[watch]
watch = ["src/", "../", "./"]

[serve]
address = "0.0.0.0"
port = 8080

[build]
release = true

[build.wasm_opt]
level = "z"

[[hooks]]
stage = "build"
command = "cp"
command_arguments = ["-r", "assets", "dist/"]
