name: Deploy to development
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: development
      pages_name: masahiro-me-dev
    secrets: inherit
